version: "2"
volumes:
  hiring-postgres-data:
    driver: local
networks:
  hiring:
services:
  vue:
    build: "front"
    container_name: "hiring-vue"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app/
    ports:
      - "8080:8080"
    environment:
      - API_PORT=80
    command: /bin/sh -c "cd front && npm install && npm run dev"
    networks:
      - hiring
  php:
    image: ambientum/php:7.2-nginx
    container_name: hiring-php
    volumes:
      - ./api:/var/www/app
    ports:
      - "80:8080"
    networks:
      - hiring
    tty: true
